language: php

php:
    - 5.4
    - 5.5
    - 5.6

before_script:
    - git config --global user.email test@test.com
    - git config --global user.name "Test User"
    - sudo composer self-update
    - composer install --dev --no-interaction --prefer-source